package envelope

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/haukened/gone/v3/internal/domain"
)

// update regenerates test/vectors from the inputs below. Run:
//
//	go test ./internal/envelope -run TestVectors -update
var update = flag.Bool("update", false, "regenerate test/vectors")

const vectorDir = "../../test/vectors"

// errCode maps package errors to language-neutral vector codes.
//
// Parameters:
//   - err: the package error to encode.
//
// Returns:
//   - string: the vector error code for err.
func errCode(err error) string {
	codes := []struct {
		err  error
		code string
	}{
		{ErrTooManyFiles, "too_many_files"},
		{ErrInvalidEnvelope, "invalid_envelope"},
		{domain.ErrInvalidVersion, "unsupported_version"},
		{ErrInvalidFragment, "invalid_fragment"},
		{ErrMalformed, "malformed"},
		{ErrInvalidPassphrase, "invalid_passphrase"},
		{ErrDecrypt, "decrypt"},
	}
	for _, c := range codes {
		if errors.Is(err, c.err) {
			return c.code
		}
	}
	return err.Error()
}

// seq returns n bytes counting up from start.
//
// Parameters:
//   - start: the first byte value.
//   - n: the number of bytes to produce.
//
// Returns:
//   - []byte: the generated byte sequence.
func seq(start byte, n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = start + byte(i)
	}
	return b
}

// hx hex-encodes bytes for vector fields.
//
// Parameters:
//   - b: the bytes to encode.
//
// Returns:
//   - string: the lowercase hexadecimal encoding.
func hx(b []byte) string {
	return hex.EncodeToString(b)
}

// marshalVector encodes v as stable, human-diffable JSON.
//
// Parameters:
//   - t: the test handle.
//   - v: the vector value to encode.
//
// Returns:
//   - []byte: the indented JSON encoding.
func marshalVector(t *testing.T, v any) []byte {
	t.Helper()
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// TestVectors checks that committed vectors match the Go implementation.
//
// Parameters:
//   - t: the test handle.
func TestVectors(t *testing.T) {
	files := map[string]any{
		"aead_v1.json":        buildAEAD(t),
		"aead_v2.json":        buildAEADV2(t),
		"envelope_gone2.json": envelopeVectors{Description: "GONE2 plaintext; binary fields are hex", Pack: buildPack(), Unpack: buildUnpack()},
		"fragment_v1.json":    buildFragments(fragmentInputs()),
		"fragment_v2.json":    buildFragments(fragmentV2Inputs()),
		"sanitize.json":       buildSanitize(),
		"server_headers.json": buildServer(),
	}
	for name, v := range files {
		checkVectorFile(t, name, v)
	}
}

// checkVectorFile verifies or updates one vector file.
//
// Parameters:
//   - t: the test handle.
//   - name: the vector file name under vectorDir.
//   - v: the vector value to compare or write.
func checkVectorFile(t *testing.T, name string, v any) {
	t.Helper()
	path := filepath.Join(vectorDir, name)
	want := marshalVector(t, v)
	if *update {
		if err := os.WriteFile(path, want, 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(path) // #nosec G304 -- fixed test path
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s is stale; regenerate with -update and review the diff", name)
	}
}
