name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: ghcr.io/haukened/gone

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (single-arch)
        uses: docker/build-push-action@v6
        env:
          TAG_REF: ${{ github.ref_name }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "## Image" >> $GITHUB_STEP_SUMMARY
          echo "ghcr.io/haukened/gone:${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY
          echo "Also tagged: latest" >> $GITHUB_STEP_SUMMARY
